### PR TITLE
ENTESB-19671 Set jolokia dependency in camel-k-runtime-bom

### PR DESCRIPTION
**Pull request by claudio4j**
ENTESB-19671 The supported trait jolokia doesn't use productised artifacts
https://issues.redhat.com/browse/ENTESB-19671

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by squakez — CHANGES_REQUESTED** [review]
I think the concept is good, altough we need to pair this change with Camel K. What we must do before though, is to have this change polished upstream first. Later, the sync process will take care of doing the synchronization in the product as well.

**Comment by claudio4j** [comment]
The sync would only work if the upstream changes were in release-1.12.x branch, right ? 
In this case, if this change is correct to set in the jboss-fuse/release-1.12.x branch, I would have to change camel-k 1.8 branch too.

**Comment by squakez** [comment]
I think we should plan to include this feature for next version, so, likely the one that match Camel K 1.10 version. My suggestion is to make all the work on the upstream `main` branch, and later we should be able to sync with the proper downstream version as well. If not, we can for sure make the manual backport.

**Comment by claudio4j** [comment]
ENTESB-19671 is a blocker, although I can confirm it with QE.

**Pull request closed without merging**
