### PR TITLE
Replaces the quarkus-camel-bom with the camel-quarkus-bom

### PR DESCRIPTION
**Pull request by phantomjinx**
* The latter bom allows for the camel-quarkus dependencies to be correctly aligned by choosing the correct bom version based on the ${camel-quarkus-version}

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by phantomjinx** [comment]
Modifying this camel-quarkus BOM allows for switching to productized versions of all the camel-quarkus dependencies downstream. Surprisingly, the quarkus-camel BOM is no longer needed since all the dependencies were seemingly downloaded and satisfied in my testing. However, I am uncertain as to whether the original BOM is still crucial for some reason, of which I'm unaware.

**Review by squakez — COMMENTED** [review]
This was the old way of providing Camel Quarkus BOM. We were required to change it (see https://issues.redhat.com/browse/ENTESB-18445) as the `camel-quarkus-bom` won't be any longer supported. Also, fyi, this part is generated dynamically by the `init-repos` script, as we change the `io.quarkus.platform` community group id to `com.redhat.quarkus.platform` which is the productized one. With this change we don't have to deal with file divergency between upstream and downstream.

**Comment by squakez** [comment]
I think we can close this.

**Comment by but-cpu** [comment]
Junk fees noted in special session 
3 bills passed meetings scheduled
Texas congressman Jefferson Texarkana.

**Pull request closed without merging**
